In [135]:
import numpy as np

def getEigen(arr):
    eigenvalues, eigenvectors = np.linalg.eig(arr)

    for i, value in enumerate(eigenvalues):
        print(f"Eigenvalue {i + 1}: {value:.3f}")
        print(f"Eigenvector {i + 1}: {np.round(eigenvectors[:, i], 3)}")
        print()


### Problem 1A

In [136]:
arr = np.zeros((10,10))

for i in range(len(arr)):
    arr[i][i] = 1

print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [137]:
getEigen(arr)

Eigenvalue 1: 1.000+0.000j
Eigenvector 1: [1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 2: 1.000+0.000j
Eigenvector 2: [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 3: 1.000+0.000j
Eigenvector 3: [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 4: 1.000+0.000j
Eigenvector 4: [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 5: 1.000+0.000j
Eigenvector 5: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 6: 1.000+0.000j
Eigenvector 6: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 7: 1.000+0.000j
Eigenvector 7: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 8: 1.000+0.000j
Eigenvector 8: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]

Eigenvalue 9: 1.000+0.000j
Eigenvector 9: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.

### Problem 1B

In [138]:
rank = np.linalg.matrix_rank(arr)
print(f"Rank: {rank}")

Rank: 10


### 1C

In [139]:
random = np.random.randint(0, 2, size=(10, 10))
print(random)

[[1 1 1 1 0 1 1 1 0 0]
 [1 0 1 0 0 1 1 0 0 1]
 [0 1 1 1 1 0 0 0 1 1]
 [1 1 1 0 1 1 1 0 1 1]
 [0 1 1 0 1 1 0 0 0 0]
 [1 1 0 1 0 1 0 1 1 0]
 [1 0 0 1 1 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 0 1 0 0 1 0]]


In [140]:
new_arr = arr + random
print(new_arr)

[[2. 1. 1. 1. 0. 1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0. 0. 1.]
 [0. 1. 2. 1. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [0. 1. 1. 0. 2. 1. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 2. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 1. 2. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1. 1.]]


In [141]:
getEigen(new_arr)

Eigenvalue 1: 6.226+0.000j
Eigenvector 1: [-0.449+0.j -0.322+0.j -0.318+0.j -0.457+0.j -0.232+0.j -0.342+0.j
 -0.393+0.j -0.064+0.j -0.153+0.j -0.18 +0.j]

Eigenvalue 2: -0.166+0.365j
Eigenvector 2: [-0.048+0.195j  0.057+0.376j -0.169-0.328j  0.42 +0.j     0.039+0.1j
 -0.009-0.251j -0.33 -0.111j  0.065-0.127j -0.382+0.095j  0.353+0.076j]

Eigenvalue 3: -0.166-0.365j
Eigenvector 3: [-0.048-0.195j  0.057-0.376j -0.169+0.328j  0.42 -0.j     0.039-0.1j
 -0.009+0.251j -0.33 +0.111j  0.065+0.127j -0.382-0.095j  0.353-0.076j]

Eigenvalue 4: 0.655+1.212j
Eigenvector 4: [ 0.526+0.j    -0.084-0.042j  0.004+0.358j -0.14 +0.051j  0.049-0.09j
  0.122-0.135j -0.366+0.116j -0.244+0.289j -0.06 +0.032j -0.206-0.427j]

Eigenvalue 5: 0.655-1.212j
Eigenvector 5: [ 0.526-0.j    -0.084+0.042j  0.004-0.358j -0.14 -0.051j  0.049+0.09j
  0.122+0.135j -0.366-0.116j -0.244-0.289j -0.06 -0.032j -0.206+0.427j]

Eigenvalue 6: 2.284+0.000j
Eigenvector 6: [ 0.178+0.j  0.026+0.j  0.523+0.j  0.225+0.j  0.394+0.j -0.437

In [142]:
rank = np.linalg.matrix_rank(new_arr)
print(f"Rank: {rank}")

Rank: 10


### 1D

In [143]:
zero_arr = np.zeros((10,10))

In [144]:
getEigen(zero_arr)

Eigenvalue 1: 0.000+0.000j
Eigenvector 1: [1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 2: 0.000+0.000j
Eigenvector 2: [0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 3: 0.000+0.000j
Eigenvector 3: [0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 4: 0.000+0.000j
Eigenvector 4: [0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 5: 0.000+0.000j
Eigenvector 5: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 6: 0.000+0.000j
Eigenvector 6: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 7: 0.000+0.000j
Eigenvector 7: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j 0.+0.j]

Eigenvalue 8: 0.000+0.000j
Eigenvector 8: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 1.+0.j 0.+0.j 0.+0.j]

Eigenvalue 9: 0.000+0.000j
Eigenvector 9: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.

In [145]:
rank = np.linalg.matrix_rank(zero_arr)
print(f"Rank: {rank}")

Rank: 0


In [146]:
values = set()
for _ in range(100000):
    random = np.random.randint(0, 2, size=(10, 10))
    new_arr = arr + random
    values.add(int(np.linalg.matrix_rank(new_arr)))

print(values)

{8, 9, 10}


Rank is 0. Every eigenvalue/eigenvector of zero matrix is zero. Most random matrices veer towards full ranks, explaining why when we add random matrices to the zero matrix, we get lots of rank = 8, 9, 10.